<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Dicom.Edge.Common\Dicom.Edge.Common.csproj" />
    <ProjectReference Include="..\..\shared\Dicom.Edge.Models\Dicom.Edge.Models.csproj" />
    <ProjectReference Include="..\..\shared\Dicom.Edge.Security\Dicom.Edge.Security.csproj" />
  </ItemGroup>

</Project>
