namespace Dicom.Edge.Models.Worklist;

/// <summary>
/// Persistence model for a worklist entry stored on the Edge Node SQLite database.
/// Populated from HL7 ORM messages pushed by the Hub and consumed by the
/// DICOM MWL C-FIND SCP to answer modality queries.
/// </summary>
public class WorklistItem
{
    // ── Identity ─────────────────────────────────────────────────────────
    public string AccessionNumber { get; set; } = default!;

    // ── Patient Level ────────────────────────────────────────────────────
    public string PatientId { get; set; } = default!;
    public string PatientName { get; set; } = default!;

    /// <summary>HL7 date string in <c>YYYYMMDD</c> format (DICOM DA).</summary>
    public string? PatientBirthDate { get; set; }

    /// <summary>DICOM CS — typically <c>M</c>, <c>F</c>, <c>O</c>.</summary>
    public string? PatientSex { get; set; }

    // ── Scheduled Procedure Step ─────────────────────────────────────────
    public DateTime ScheduledDate { get; set; }
    public string Modality { get; set; } = default!;

    /// <summary>
    /// AE Title of the modality that will perform the study (DICOM 0040,0001).
    /// Filled from HL7 OBR-21 / OBR-22 when available.
    /// </summary>
    public string? ScheduledStationAeTitle { get; set; }

    /// <summary>DICOM 0040,0006 — physician performing the procedure.</summary>
    public string? ScheduledPerformingPhysicianName { get; set; }

    /// <summary>DICOM 0040,0009 — Scheduled Procedure Step ID.</summary>
    public string? ScheduledProcedureStepId { get; set; }

    // ── Study / Requested Procedure ──────────────────────────────────────
    public string ProcedureDescription { get; set; } = default!;

    /// <summary>DICOM 0040,1001 — Requested Procedure ID (from HL7 OBR-44).</summary>
    public string? RequestedProcedureId { get; set; }

    /// <summary>DICOM 0008,0090 — Referring physician.</summary>
    public string? ReferringPhysicianName { get; set; }

    /// <summary>DICOM 0020,000D — Study Instance UID (may be generated by Hub).</summary>
    public string? StudyInstanceUid { get; set; }
}
