// <auto-generated />
using System;
using Dicom.Edge.Hub.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dicom.Edge.Hub.Persistence.Migrations
{
    [DbContext(typeof(HubDbContext))]
    partial class HubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Audit.HubAuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("action");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_hub_audit_logs");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_hub_audit_logs_correlation_id")
                        .HasFilter("correlation_id IS NOT NULL");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_hub_audit_logs_created_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_hub_audit_logs_entity_type_entity_id")
                        .HasFilter("entity_id IS NOT NULL");

                    b.HasIndex("EventType", "CreatedAt")
                        .HasDatabaseName("ix_hub_audit_logs_event_type_created_at");

                    b.ToTable("hub_audit_logs", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Cleanup.StudyCleanupPolicy", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<bool>("ApplyToAllNodes")
                        .HasColumnType("boolean")
                        .HasColumnName("apply_to_all_nodes");

                    b.Property<TimeOnly>("CleanupTimeUtc")
                        .HasColumnType("time without time zone")
                        .HasColumnName("cleanup_time_utc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_executed_at");

                    b.Property<int>("LastExecutionErrors")
                        .HasColumnType("integer")
                        .HasColumnName("last_execution_errors");

                    b.Property<int>("LastExecutionStudiesDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("last_execution_studies_deleted");

                    b.Property<int>("MaxStudiesPerRun")
                        .HasColumnType("integer")
                        .HasColumnName("max_studies_per_run");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("modality");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("retention_days");

                    b.Property<string>("SpecificNodeIdsCsv")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("specific_node_ids_csv");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_study_cleanup_policies");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_study_cleanup_policies_is_enabled");

                    b.HasIndex("Modality")
                        .HasDatabaseName("ix_study_cleanup_policies_modality");

                    b.ToTable("study_cleanup_policies", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Configuration.SystemSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_encrypted");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read_only");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_system_settings");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_system_settings_category");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.HealthChecks.HealthCheckRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<int?>("ActiveAssociations")
                        .HasColumnType("integer")
                        .HasColumnName("active_associations");

                    b.Property<double?>("BandwidthMbps")
                        .HasColumnType("double precision")
                        .HasColumnName("bandwidth_mbps");

                    b.Property<double?>("CpuUsagePercent")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_usage_percent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("DiskAvailableMb")
                        .HasColumnType("bigint")
                        .HasColumnName("disk_available_mb");

                    b.Property<double?>("LatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("latency_ms");

                    b.Property<long?>("MemoryUsageMb")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_usage_mb");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("node_id");

                    b.Property<int?>("QueuedStudies")
                        .HasColumnType("integer")
                        .HasColumnName("queued_studies");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("ReportedNodeStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reported_node_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UptimeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("uptime_seconds");

                    b.HasKey("Id")
                        .HasName("pk_health_check_records");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_health_check_records_node_id");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_health_check_records_received_at");

                    b.ToTable("health_check_records", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.HealthChecks.PacsCEchoResult", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("error_message");

                    b.Property<string>("HealthCheckRecordId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("health_check_record_id");

                    b.Property<string>("PacsAeTitle")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("pacs_ae_title");

                    b.Property<string>("PacsId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pacs_id");

                    b.Property<double?>("ResponseTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("response_time_ms");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pacs_cecho_results");

                    b.HasIndex("CheckedAt")
                        .HasDatabaseName("ix_pacs_cecho_results_checked_at");

                    b.HasIndex("HealthCheckRecordId")
                        .HasDatabaseName("ix_pacs_cecho_results_health_check_record_id");

                    b.HasIndex("PacsId")
                        .HasDatabaseName("ix_pacs_cecho_results_pacs_id");

                    b.ToTable("pacs_cecho_results", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.NodeConfig.NodeConfigurationProfile", b =>
                {
                    b.Property<string>("NodeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("node_id");

                    b.Property<string>("SettingKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("setting_key");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsOverridden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_overridden");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("value_type");

                    b.HasKey("NodeId", "SettingKey")
                        .HasName("pk_node_configuration_profiles");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_node_configuration_profiles_node_id");

                    b.HasIndex("NodeId", "Category")
                        .HasDatabaseName("ix_node_configuration_profiles_node_id_category");

                    b.ToTable("node_configuration_profiles", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Nodes.Node", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("ApiEndpoint")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("api_endpoint");

                    b.Property<long>("AvailableStorageMb")
                        .HasColumnType("bigint")
                        .HasColumnName("available_storage_mb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("ErrorsLast24Hours")
                        .HasColumnType("integer")
                        .HasColumnName("errors_last24_hours");

                    b.Property<string>("FacilityName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("facility_name");

                    b.Property<int>("HealthCheckIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("health_check_interval_seconds");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location");

                    b.Property<long>("MaxStorageMb")
                        .HasColumnType("bigint")
                        .HasColumnName("max_storage_mb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.Property<int>("TotalStudiesReceived")
                        .HasColumnType("integer")
                        .HasColumnName("total_studies_received");

                    b.Property<int>("TotalStudiesSent")
                        .HasColumnType("integer")
                        .HasColumnName("total_studies_sent");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_nodes");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_nodes_is_deleted");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_nodes_is_enabled");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_nodes_status");

                    b.ToTable("nodes", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Nodes.NodePacsAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<int>("CEchoIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("c_echo_interval_seconds");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("InheritedFromHub")
                        .HasColumnType("boolean")
                        .HasColumnName("inherited_from_hub");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastCEchoAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_c_echo_at");

                    b.Property<bool?>("LastCEchoSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("last_c_echo_success");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("node_id");

                    b.Property<string>("PacsId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pacs_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_node_pacs_assignments");

                    b.HasIndex("NodeId", "PacsId", "IsActive")
                        .HasDatabaseName("ix_node_pacs_assignments_node_id_pacs_id_is_active");

                    b.ToTable("node_pacs_assignments", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Notifications.WhatsAppNotification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageTemplate")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("message_template");

                    b.Property<string>("PacsViewerLink")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("pacs_viewer_link");

                    b.Property<string>("PatientId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("patient_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StudyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("study_id");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("triggered_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_whatsapp_notifications");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_whatsapp_notifications_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_whatsapp_notifications_status");

                    b.HasIndex("StudyId")
                        .HasDatabaseName("ix_whatsapp_notifications_study_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_whatsapp_notifications_status_created_at")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("whatsapp_notifications", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Pacs.PacsSendAudit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<string>("PacsAeTitle")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("pacs_ae_title");

                    b.Property<string>("PacsId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pacs_id");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("response_code");

                    b.Property<long?>("ResponseTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("response_time_ms");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("StudyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("study_id");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pacs_send_audits");

                    b.HasIndex("PacsId")
                        .HasDatabaseName("ix_pacs_send_audits_pacs_id");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("ix_pacs_send_audits_sent_at");

                    b.HasIndex("StudyId")
                        .HasDatabaseName("ix_pacs_send_audits_study_id");

                    b.HasIndex("StudyId", "Attempt")
                        .HasDatabaseName("ix_pacs_send_audits_study_id_attempt");

                    b.ToTable("pacs_send_audits", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Pacs.PacsServer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("host_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_global");

                    b.Property<bool>("IsReachable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reachable");

                    b.Property<DateTime?>("LastCEchoAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_c_echo_at");

                    b.Property<bool>("LastCEchoSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("last_c_echo_success");

                    b.Property<int>("MaxConcurrentAssociations")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrent_associations");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("SupportedModalitiesCsv")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("supported_modalities_csv");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pacs_servers");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_pacs_servers_is_enabled");

                    b.HasIndex("IsGlobal")
                        .HasDatabaseName("ix_pacs_servers_is_global");

                    b.ToTable("pacs_servers", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Patients.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByNodeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by_node_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FacilitySource")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("facility_source");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("IssuerOfPatientId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("issuer_of_patient_id");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("OtherPatientIds")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("other_patient_ids");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("patient_name");

                    b.Property<string>("Sex")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sex");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_patients_is_active");

                    b.HasIndex("PatientName")
                        .HasDatabaseName("ix_patients_patient_name");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Routing.Hl7RoutingRule", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastMatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_matched_at");

                    b.Property<int>("MatchCount")
                        .HasColumnType("integer")
                        .HasColumnName("match_count");

                    b.Property<string>("MatchMessageType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("match_message_type");

                    b.Property<string>("MatchSendingApplication")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("match_sending_application");

                    b.Property<string>("MatchSendingFacility")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("match_sending_facility");

                    b.Property<string>("MatchTriggerEvent")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("match_trigger_event");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("TargetNodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_node_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hl7_routing_rules");

                    b.HasIndex("IsEnabled", "Priority")
                        .HasDatabaseName("ix_hl7_routing_rules_active");

                    b.ToTable("hl7_routing_rules", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Studies.Study", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("AccessionNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("accession_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("CurrentStatusSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_status_since");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("FirstImageReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_image_received_at");

                    b.Property<int>("InstanceCount")
                        .HasColumnType("integer")
                        .HasColumnName("instance_count");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_urgent");

                    b.Property<DateTime?>("LastImageReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_image_received_at");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<int>("PacsSendAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("pacs_send_attempts");

                    b.Property<string>("PacsSendLastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("pacs_send_last_error");

                    b.Property<string>("PatientId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("patient_id");

                    b.Property<string>("PatientName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("patient_name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("ReceivingAeTitle")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("receiving_ae_title");

                    b.Property<string>("ReferringPhysician")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("referring_physician");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SentToPacsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_to_pacs_at");

                    b.Property<int>("SeriesCount")
                        .HasColumnType("integer")
                        .HasColumnName("series_count");

                    b.Property<string>("SourceAeTitle")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source_ae_title");

                    b.Property<string>("SourceNodeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_node_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StudyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("study_date");

                    b.Property<string>("StudyDescription")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("study_description");

                    b.Property<string>("TargetPacsId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_pacs_id");

                    b.Property<long>("TotalSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_size_bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("WorklistReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("worklist_read_at");

                    b.Property<string>("WorklistReadByModality")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("worklist_read_by_modality");

                    b.HasKey("Id")
                        .HasName("pk_studies");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_studies_patient_id");

                    b.HasIndex("SourceNodeId")
                        .HasDatabaseName("ix_studies_source_node_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_studies_status");

                    b.HasIndex("StudyDate")
                        .HasDatabaseName("ix_studies_study_date");

                    b.HasIndex("IsDeleted", "CreatedAt")
                        .HasDatabaseName("ix_studies_is_deleted_created_at");

                    b.ToTable("studies", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Studies.StudySeries", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("InstanceCount")
                        .HasColumnType("integer")
                        .HasColumnName("instance_count");

                    b.Property<string>("Modality")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("modality");

                    b.Property<string>("SeriesDescription")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("series_description");

                    b.Property<string>("SeriesInstanceUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("series_instance_uid");

                    b.Property<int?>("SeriesNumber")
                        .HasColumnType("integer")
                        .HasColumnName("series_number");

                    b.Property<string>("StudyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("study_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_study_series");

                    b.HasIndex("SeriesInstanceUid")
                        .HasDatabaseName("ix_study_series_series_instance_uid");

                    b.HasIndex("StudyId")
                        .HasDatabaseName("ix_study_series_study_id");

                    b.ToTable("study_series", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Studies.StudyStatusAudit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedByNodeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("changed_by_node_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("new_status");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<string>("StudyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("study_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_study_status_audits");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("ix_study_status_audits_changed_at");

                    b.HasIndex("StudyId")
                        .HasDatabaseName("ix_study_status_audits_study_id");

                    b.ToTable("study_status_audits", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Entities.Hl7Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessionNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("accession_number");

                    b.Property<string>("ClientEndpoint")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_endpoint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<int>("DispatchAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("dispatch_attempts");

                    b.Property<string>("DispatchError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("dispatch_error");

                    b.Property<string>("DispatchStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("dispatch_status");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("Hl7Version")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("hl7_version");

                    b.Property<string>("MessageControlId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("message_control_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("message_type");

                    b.Property<string>("PatientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("patient_id");

                    b.Property<string>("PatientName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("patient_name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTime?>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<int>("ReceivedOnPort")
                        .HasColumnType("integer")
                        .HasColumnName("received_on_port");

                    b.Property<DateTime?>("RoutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("routed_at");

                    b.Property<string>("SendingApplication")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sending_application");

                    b.Property<string>("SendingFacility")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sending_facility");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TargetNodeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_node_id");

                    b.Property<string>("TargetNodeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_node_name");

                    b.Property<string>("TriggerEvent")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trigger_event");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.HasKey("Id")
                        .HasName("pk_hl7_messages");

                    b.HasIndex("DispatchStatus")
                        .HasDatabaseName("ix_hl7_messages_dispatch_status");

                    b.HasIndex("MessageType")
                        .HasDatabaseName("ix_hl7_messages_message_type");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_hl7_messages_received_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_hl7_messages_status");

                    b.HasIndex("DispatchStatus", "Priority", "ReceivedAt")
                        .HasDatabaseName("ix_hl7_messages_dispatch_queue");

                    b.ToTable("hl7_messages", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.HealthChecks.PacsCEchoResult", b =>
                {
                    b.HasOne("Dicom.Edge.Hub.Domain.Aggregates.HealthChecks.HealthCheckRecord", null)
                        .WithMany("PacsResults")
                        .HasForeignKey("HealthCheckRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pacs_cecho_results_health_check_records_health_check_record~");
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Nodes.Node", b =>
                {
                    b.OwnsOne("Dicom.Edge.Hub.Domain.ValueObjects.AeTitle", "AeTitle", b1 =>
                        {
                            b1.Property<string>("NodeId")
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("ae_title");

                            b1.HasKey("NodeId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_nodes_ae_title");

                            b1.ToTable("nodes");

                            b1.WithOwner()
                                .HasForeignKey("NodeId")
                                .HasConstraintName("fk_nodes_nodes_node_id");
                        });

                    b.Navigation("AeTitle")
                        .IsRequired();
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Nodes.NodePacsAssignment", b =>
                {
                    b.HasOne("Dicom.Edge.Hub.Domain.Aggregates.Nodes.Node", null)
                        .WithMany("PacsAssignments")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_pacs_assignments_nodes_node_id");
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Pacs.PacsServer", b =>
                {
                    b.OwnsOne("Dicom.Edge.Hub.Domain.ValueObjects.AeTitle", "AeTitle", b1 =>
                        {
                            b1.Property<string>("PacsServerId")
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("ae_title");

                            b1.HasKey("PacsServerId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_pacs_servers_ae_title");

                            b1.ToTable("pacs_servers");

                            b1.WithOwner()
                                .HasForeignKey("PacsServerId")
                                .HasConstraintName("fk_pacs_servers_pacs_servers_pacs_server_id");
                        });

                    b.Navigation("AeTitle")
                        .IsRequired();
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Patients.Patient", b =>
                {
                    b.OwnsOne("Dicom.Edge.Hub.Domain.ValueObjects.PatientIdentifier", "PatientDicomId", b1 =>
                        {
                            b1.Property<string>("PatientId")
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("patient_dicom_id");

                            b1.HasKey("PatientId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("ix_patients_patient_dicom_id");

                            b1.ToTable("patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientId")
                                .HasConstraintName("fk_patients_patients_patient_id");
                        });

                    b.Navigation("PatientDicomId")
                        .IsRequired();
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Studies.Study", b =>
                {
                    b.OwnsOne("Dicom.Edge.Hub.Domain.ValueObjects.DicomUid", "StudyInstanceUid", b1 =>
                        {
                            b1.Property<string>("StudyId")
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("study_instance_uid");

                            b1.HasKey("StudyId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_studies_study_instance_uid");

                            b1.ToTable("studies");

                            b1.WithOwner()
                                .HasForeignKey("StudyId")
                                .HasConstraintName("fk_studies_studies_study_id");
                        });

                    b.Navigation("StudyInstanceUid")
                        .IsRequired();
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Studies.StudySeries", b =>
                {
                    b.HasOne("Dicom.Edge.Hub.Domain.Aggregates.Studies.Study", null)
                        .WithMany("Series")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_study_series_studies_study_id");
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Studies.StudyStatusAudit", b =>
                {
                    b.HasOne("Dicom.Edge.Hub.Domain.Aggregates.Studies.Study", null)
                        .WithMany("StatusAudits")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_study_status_audits_studies_study_id");
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.HealthChecks.HealthCheckRecord", b =>
                {
                    b.Navigation("PacsResults");
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Nodes.Node", b =>
                {
                    b.Navigation("PacsAssignments");
                });

            modelBuilder.Entity("Dicom.Edge.Hub.Domain.Aggregates.Studies.Study", b =>
                {
                    b.Navigation("Series");

                    b.Navigation("StatusAudits");
                });
#pragma warning restore 612, 618
        }
    }
}
