// <auto-generated />
using System;
using Dicom.Edge.Node.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dicom.Edge.Node.Persistence.Migrations
{
    [DbContext(typeof(EdgeNodeDbContext))]
    [Migration("20260507031336_AddNodePacsServers")]
    partial class AddNodePacsServers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Dicom.Edge.Models.Audit.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("DestinationAeTitle")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("destination_ae_title");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<string>("EdgeNodeId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("edge_node_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_success");

                    b.Property<string>("PatientId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("patient_id");

                    b.Property<int>("Severity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("severity");

                    b.Property<string>("SourceAeTitle")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_ae_title");

                    b.Property<string>("StudyInstanceUid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("study_instance_uid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.Property<string>("correlation_id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("px_audit_patient_id")
                        .HasFilter("\"patient_id\" IS NOT NULL");

                    b.HasIndex("StudyInstanceUid")
                        .HasDatabaseName("px_audit_study_instance_uid")
                        .HasFilter("\"study_instance_uid\" IS NOT NULL");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_timestamp");

                    b.HasIndex("correlation_id")
                        .HasDatabaseName("px_audit_correlation_id")
                        .HasFilter("\"correlation_id\" IS NOT NULL");

                    b.HasIndex("EventType", "Timestamp")
                        .HasDatabaseName("ix_audit_event_type_time");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Models.Configuration.ModalityConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AETitle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("ae_title");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultDestination")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_destination");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("department");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_online");

                    b.Property<DateTime?>("LastConnectionAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_connection_at");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<int>("MaxConcurrentConnections")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5)
                        .HasColumnName("max_concurrent_conn");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(104)
                        .HasColumnName("port");

                    b.Property<bool>("RequiresAuth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("requires_auth");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Timeout")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timeout_minutes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("synced_from_hub_at")
                        .HasColumnType("TEXT")
                        .HasColumnName("synced_from_hub_at");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("AETitle")
                        .IsUnique()
                        .HasDatabaseName("uq_modality_ae_title");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_modality_is_enabled");

                    b.ToTable("modality_configurations", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Models.Core.DicomInstance", b =>
                {
                    b.Property<string>("SopInstanceUid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("sop_instance_uid");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<int>("InstanceNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instance_number");

                    b.Property<string>("SeriesInstanceUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("series_instance_uid");

                    b.Property<string>("SopClassUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("sop_class_uid");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<long>("file_size_bytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("transfer_syntax_uid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("transfer_syntax_uid");

                    b.HasKey("SopInstanceUid");

                    b.HasIndex("FilePath")
                        .IsUnique()
                        .HasDatabaseName("uq_instance_file_path");

                    b.HasIndex("SeriesInstanceUid")
                        .HasDatabaseName("ix_instance_series_instance_uid");

                    b.ToTable("dicom_instances", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Models.Core.DicomSeries", b =>
                {
                    b.Property<string>("SeriesInstanceUid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("series_instance_uid");

                    b.Property<int>("InstanceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("instance_count");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("modality");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("study_instance_uid");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("SeriesInstanceUid");

                    b.HasIndex("Modality")
                        .HasDatabaseName("ix_series_modality");

                    b.HasIndex("StudyInstanceUid")
                        .HasDatabaseName("ix_series_study_instance_uid");

                    b.ToTable("dicom_series", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Models.Core.DicomStudy", b =>
                {
                    b.Property<string>("StudyInstanceUid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("study_instance_uid");

                    b.Property<string>("AccessionNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("accession_number");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EdgeNodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("edge_node_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int>("InstanceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("instance_count");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastImageReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_image_at");

                    b.Property<string>("PatientId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("patient_id");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("patient_name");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_at");

                    b.Property<string>("ReferringPhysician")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("referring_physician");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SentToHubAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("sent_to_hub_at");

                    b.Property<string>("SourceAeTitle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_ae_title");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<DateTime>("StudyDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("study_date");

                    b.Property<string>("StudyDescription")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("study_description");

                    b.Property<long>("TotalSizeBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_size_bytes");

                    b.Property<string>("correlation_id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("StudyInstanceUid");

                    b.HasIndex("AccessionNumber")
                        .HasDatabaseName("ix_studies_accession_number")
                        .HasFilter("\"accession_number\" IS NOT NULL");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_studies_patient_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("px_studies_not_sent")
                        .HasFilter("\"sent_to_hub_at\" IS NULL AND \"is_deleted\" = 0");

                    b.HasIndex("StudyDate")
                        .HasDatabaseName("ix_studies_study_date");

                    b.HasIndex("correlation_id")
                        .HasDatabaseName("px_studies_correlation_id")
                        .HasFilter("\"correlation_id\" IS NOT NULL");

                    b.HasIndex("SourceAeTitle", "Status")
                        .HasDatabaseName("ix_studies_source_ae_status");

                    b.HasIndex("Status", "ReceivedAt")
                        .HasDatabaseName("ix_studies_status_received_at");

                    b.HasIndex("IsDeleted", "Status", "ReceivedAt")
                        .HasDatabaseName("ix_studies_cleanup");

                    b.ToTable("dicom_studies", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Models.Dicom.DicomAssociation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AcceptedPresentationContexts")
                        .HasColumnType("TEXT")
                        .HasColumnName("accepted_contexts");

                    b.Property<long>("BytesReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("bytes_received");

                    b.Property<string>("CalledAeTitle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("called_ae_title");

                    b.Property<string>("CallingAeTitle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("calling_ae_title");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("connected_at");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("disconnected_at");

                    b.Property<string>("EdgeNodeId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("edge_node_id");

                    b.Property<int>("ImagesReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("images_received");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("RemoteIpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_ip");

                    b.Property<int>("RemotePort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("remote_port");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CallingAeTitle")
                        .HasDatabaseName("ix_association_calling_ae_title");

                    b.HasIndex("ConnectedAt")
                        .HasDatabaseName("ix_association_connected_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_association_status");

                    b.ToTable("dicom_associations", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Models.Edge.EdgeQueueItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("destination");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int>("InstanceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("instance_count");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<DateTime?>("LastAttempt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_attempt_at");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_by");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("context_json");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_retry_at");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5)
                        .HasColumnName("priority");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<long>("SizeBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("size_bytes");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("study_instance_uid");

                    b.HasKey("Id");

                    b.HasIndex("StudyInstanceUid")
                        .HasDatabaseName("ix_queue_study_instance_uid");

                    b.HasIndex("IsLocked", "LockedAt")
                        .HasDatabaseName("px_queue_stale_locks")
                        .HasFilter("\"is_locked\" = 1");

                    b.HasIndex("Status", "Priority", "NextRetryAt")
                        .HasDatabaseName("ix_queue_dequeue");

                    b.ToTable("edge_queue_items", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Models.Edge.TransferError", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalContext")
                        .HasColumnType("TEXT")
                        .HasColumnName("context_json");

                    b.Property<string>("EdgeNodeId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("edge_node_id");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int>("ErrorType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("error_type");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_resolved");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<int>("RetryAttempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_attempt");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT")
                        .HasColumnName("stack_trace");

                    b.Property<string>("StudyInstanceUid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("study_instance_uid");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_errors_occurred_at");

                    b.HasIndex("StudyInstanceUid")
                        .HasDatabaseName("ix_errors_study_instance_uid");

                    b.HasIndex("ErrorType", "IsResolved")
                        .HasDatabaseName("px_errors_unresolved")
                        .HasFilter("\"is_resolved\" = 0");

                    b.ToTable("transfer_errors", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Models.Metrics.StudyMetrics", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double>("AverageImageSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0)
                        .HasColumnName("avg_image_size");

                    b.Property<DateTime>("FirstImageAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_image_at");

                    b.Property<int>("InstancesFailed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("instances_failed");

                    b.Property<int>("InstancesReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("instances_received");

                    b.Property<DateTime>("LastImageAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_image_at");

                    b.Property<long>("ReceptionDuration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reception_ms");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("study_instance_uid");

                    b.Property<long>("TotalSizeBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_size_bytes");

                    b.Property<long?>("TransferDuration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transfer_ms");

                    b.HasKey("Id");

                    b.HasIndex("FirstImageAt")
                        .HasDatabaseName("ix_metrics_first_image_at");

                    b.HasIndex("StudyInstanceUid")
                        .IsUnique()
                        .HasDatabaseName("uq_metrics_study_instance_uid");

                    b.ToTable("study_metrics", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Models.Patient.DicomPatient", b =>
                {
                    b.Property<string>("PatientId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("patient_id");

                    b.Property<string>("AccessionNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("accession_number");

                    b.Property<string>("Allergies")
                        .HasColumnType("TEXT")
                        .HasColumnName("allergies");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT")
                        .HasColumnName("comments");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstitutionName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("institution_name");

                    b.Property<string>("MedicalRecordNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("medical_record_number");

                    b.Property<string>("PatientAge")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("patient_age");

                    b.Property<double?>("PatientHeightM")
                        .HasColumnType("REAL")
                        .HasColumnName("patient_height_m");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("patient_name");

                    b.Property<double?>("PatientWeightKg")
                        .HasColumnType("REAL")
                        .HasColumnName("patient_weight_kg");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferringPhysician")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("referring_physician");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("sex");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("PatientId");

                    b.HasIndex("PatientName")
                        .HasDatabaseName("ix_patient_name");

                    b.ToTable("dicom_patients", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Models.Routing.RoutingRule", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccessionNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("accession_number");

                    b.Property<bool>("AnonymizeBeforeSending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("anonymize");

                    b.Property<bool>("ArchiveImmediately")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("archive_immediately");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomConditionJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("custom_condition");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("department");

                    b.Property<string>("DestinationAeTitle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("destination_ae");

                    b.Property<string>("InstitutionName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("institution_name");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastMatchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_matched_at");

                    b.Property<int>("MatchCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("match_count");

                    b.Property<int?>("MaxInstanceCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_instance_count");

                    b.Property<int?>("MinInstanceCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_instance_count");

                    b.Property<string>("Modality")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("modality");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(100)
                        .HasColumnName("priority");

                    b.Property<bool>("SendToHub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("send_to_hub");

                    b.Property<bool>("SendToPacs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("send_to_pacs");

                    b.Property<string>("SourceAeTitle")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_ae_title");

                    b.Property<string>("StudyDescriptionContains")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("study_desc_contains");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Priority", "IsEnabled")
                        .HasDatabaseName("ix_routing_priority_enabled");

                    b.ToTable("routing_rules", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Models.Storage.StudyArchive", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ArchiveLocation")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("archive_location");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CompressionRatio")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("DeleteScheduledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_scheduled_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLegalHold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reason");

                    b.Property<long>("SizeBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("size_bytes");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("study_instance_uid");

                    b.HasKey("Id");

                    b.HasIndex("DeleteScheduledAt")
                        .HasDatabaseName("px_archive_pending_delete")
                        .HasFilter("\"is_deleted\" = 0 AND \"delete_scheduled_at\" IS NOT NULL");

                    b.HasIndex("StudyInstanceUid")
                        .HasDatabaseName("ix_archive_study_instance_uid");

                    b.ToTable("study_archives", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Models.Transfer.StudyTransfer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("BytesTransferred")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("bytes_transferred");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("EdgeNodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("edge_node_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int>("InstancesFailed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("instances_failed");

                    b.Property<int>("InstancesTransferred")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("instances_xferred");

                    b.Property<string>("Modality")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("modality");

                    b.Property<string>("PatientId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("patient_id");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("SourceAeTitle")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_ae_title");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StudyDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("study_date");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("study_instance_uid");

                    b.Property<int>("TotalInstances")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("total_instances");

                    b.Property<long>("TotalSizeBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_size_bytes");

                    b.Property<string>("TransferMethod")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("transfer_method");

                    b.HasKey("Id");

                    b.HasIndex("StudyInstanceUid")
                        .HasDatabaseName("ix_transfer_study_instance_uid");

                    b.HasIndex("Status", "StartedAt")
                        .HasDatabaseName("ix_transfer_status_started_at");

                    b.ToTable("study_transfers", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Models.Worklist.WorklistItem", b =>
                {
                    b.Property<string>("AccessionNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("accession_number");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("modality");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("patient_id");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("patient_name");

                    b.Property<string>("ProcedureDescription")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("procedure_description");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduled_date");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("AccessionNumber");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_worklist_patient_id");

                    b.HasIndex("status")
                        .HasDatabaseName("ix_worklist_status");

                    b.HasIndex("ScheduledDate", "Modality")
                        .HasDatabaseName("ix_worklist_scheduled_date_modality");

                    b.ToTable("worklist_items", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Node.Persistence.Entities.NodePacsServer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AeTitle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("ae_title");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER")
                        .HasColumnName("port");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10)
                        .HasColumnName("priority");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("synced_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AeTitle")
                        .HasDatabaseName("ix_node_pacs_servers_ae_title");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_node_pacs_servers_is_enabled");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_node_pacs_servers_priority");

                    b.ToTable("node_pacs_servers", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Node.Persistence.Entities.NodeRegistrationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("HubAssignedVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("hub_assigned_version");

                    b.Property<string>("HubBaseUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("hub_base_url");

                    b.Property<string>("HubNodeId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("hub_node_id");

                    b.Property<DateTime?>("LastConfigSyncAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_config_sync_at");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<DateTime?>("RegisteredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("registered_at");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("registration_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("node_registration", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Node.Persistence.Entities.NodeSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read_only");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("value_type");

                    b.HasKey("Key");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_node_settings_category");

                    b.ToTable("node_settings", (string)null);
                });

            modelBuilder.Entity("Dicom.Edge.Models.Core.DicomInstance", b =>
                {
                    b.HasOne("Dicom.Edge.Models.Core.DicomSeries", null)
                        .WithMany("Instances")
                        .HasForeignKey("SeriesInstanceUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dicom.Edge.Models.Core.DicomSeries", b =>
                {
                    b.HasOne("Dicom.Edge.Models.Core.DicomStudy", null)
                        .WithMany("Series")
                        .HasForeignKey("StudyInstanceUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dicom.Edge.Models.Core.DicomStudy", b =>
                {
                    b.HasOne("Dicom.Edge.Models.Patient.DicomPatient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dicom.Edge.Models.Core.DicomSeries", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("Dicom.Edge.Models.Core.DicomStudy", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
