<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\EdgeGuard.Edge.Application\EdgeGuard.Edge.Application.csproj" />
    <ProjectReference Include="..\EdgeGuard.Edge.Infrastructure\EdgeGuard.Edge.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
