<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Dicom.Edge.Node-723f0a37-ab76-4935-bb32-101289c1ab99</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Dicom.Edge.Diagnostics\Dicom.Edge.Diagnostics.csproj" />
    <ProjectReference Include="..\Dicom.Edge.Node.Persistence\Dicom.Edge.Node.Persistence.csproj" />
    <ProjectReference Include="..\Dicom.Edge.Node.Storage\Dicom.Edge.Node.Storage.csproj" />
  </ItemGroup>
</Project>
