<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Dicom.Edge.Hub.Api-a1b2c3d4-e5f6-7890-abcd-ef1234567890</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dicom.Edge.Hub.Domain\Dicom.Edge.Hub.Domain.csproj" />
    <ProjectReference Include="..\Dicom.Edge.Hub.Application\Dicom.Edge.Hub.Application.csproj" />
    <ProjectReference Include="..\Dicom.Edge.Hub.Persistence\Dicom.Edge.Hub.Persistence.csproj" />
    <ProjectReference Include="..\Dicom.Edge.Hub.Infrastructure\Dicom.Edge.Hub.Infrastructure.csproj" />
    <ProjectReference Include="..\Dicom.Edge.Hub.Diagnostics\Dicom.Edge.Hub.Diagnostics.csproj" />
  </ItemGroup>

</Project>
