export const API_ROUTES = {
  AUTH: {
    LOGIN: '/auth/login',
    REFRESH: '/auth/refresh',
    REVOKE: '/auth/revoke',
    REVOKE_ALL: '/auth/revoke-all',
    ME: '/auth/me',
  },
  DASHBOARD: {
    SUMMARY: '/dashboard/summary',
  },
  STUDIES: {
    LIST: '/studies',
    BY_ID: (id: string) => `/studies/${id}`,
    BY_UID: (uid: string) => `/studies/by-uid/${uid}`,
    BY_PATIENT: (patientId: string) => `/studies/by-patient/${patientId}`,
    BY_NODE: (nodeId: string) => `/studies/by-node/${nodeId}`,
    PENDING_PACS: '/studies/pending-pacs',
    COUNT: '/studies/count',
    STATUS: (id: string) => `/studies/${id}/status`,
    EXPORT: '/studies/export',
    REPORT: (id: string) => `/studies/${id}/report`,
    REPORT_PDF: (id: string) => `/studies/${id}/report/pdf`,
    REPORT_QR: (id: string) => `/studies/${id}/report/qr`,
  },
  NOTIFICATION_TEMPLATES: {
    LIST: '/notification-templates',
    BY_ID: (id: string) => `/notification-templates/${id}`,
    TAGS: '/notification-templates/tags',
    PREVIEW: '/notification-templates/preview',
  },
  NOTIFICATION_SETTINGS: {
    GET: '/notification-settings',
    AUTO_MODE: '/notification-settings/auto-mode',
    SMTP_TEST: '/notification-settings/smtp/test',
  },
  PATIENTS: {
    LIST: '/patients',
    BY_ID: (id: string) => `/patients/${id}`,
    BY_DICOM_ID: (dicomId: string) => `/patients/by-dicom-id/${dicomId}`,
    SEARCH: '/patients/search',
    COUNT: '/patients/count',
    EXPORT: '/patients/export',
    IMPORT: '/patients/import',
  },
  NODES: {
    LIST: '/nodes',
    ALL: '/nodes/all',
    ACTIVE: '/nodes/active',
    BY_ID: (id: string) => `/nodes/${id}`,
    ENABLE: (id: string) => `/nodes/${id}/enable`,
    DISABLE: (id: string) => `/nodes/${id}/disable`,
    COUNT: '/nodes/count',
    ASSIGN_PACS: (nodeId: string, pacsId: string) => `/nodes/${nodeId}/pacs/${pacsId}`,
    UNASSIGN_PACS: (nodeId: string, pacsId: string) => `/nodes/${nodeId}/pacs/${pacsId}`,
    TELEMETRY: (id: string) => `/nodes/${id}/telemetry`,
    PACS_ECHO: (id: string) => `/nodes/${id}/pacs-echo`,
  },
  PACS_SERVERS: {
    LIST: '/pacs-servers',
    BY_ID: (id: string) => `/pacs-servers/${id}`,
    ENABLE: (id: string) => `/pacs-servers/${id}/enable`,
    DISABLE: (id: string) => `/pacs-servers/${id}/disable`,
  },
  ROUTING_RULES: {
    LIST: '/routing-rules',
    BY_ID: (id: string) => `/routing-rules/${id}`,
    ENABLE: (id: string) => `/routing-rules/${id}/enable`,
    DISABLE: (id: string) => `/routing-rules/${id}/disable`,
    PRIORITY: (id: string) => `/routing-rules/${id}/priority`,
  },
  HL7_STATUS: {
    STATUS: '/hl7-status/status',
    RECENT_MESSAGES: '/hl7-status/recent-messages',
    MESSAGE_DETAIL: (id: string) => `/hl7-status/messages/${id}`,
    REPROCESS: (id: string) => `/hl7-status/messages/${id}/reprocess`,
  },
  QUEUE_MONITORING: {
    SUMMARY: '/queue-monitoring/summary',
    BY_STATUS: (status: string) => `/queue-monitoring/by-dispatch-status/${status}`,
    QUEUED: '/queue-monitoring/queued',
  },
  WHATSAPP: {
    CONFIG_STATUS: '/whatsapp/config-status',
    TAGS: '/whatsapp/tags',
    TEMPLATES: '/whatsapp/templates',
    TEMPLATE_BY_ID: (id: string) => `/whatsapp/templates/${id}`,
    AUTO_SEND_RULES: '/whatsapp/auto-send-rules',
    AUTO_SEND_RULE_BY_ID: (id: string) => `/whatsapp/auto-send-rules/${id}`,
    SEND: '/whatsapp/send',
    NOTIFICATIONS_BY_STUDY: (studyId: string) => `/whatsapp/notifications/by-study/${studyId}`,
  },
  USERS: {
    LIST: '/users',
    BY_ID: (id: string) => `/users/${id}`,
    PROFILE: (id: string) => `/users/${id}/profile`,
    DEACTIVATE: (id: string) => `/users/${id}/deactivate`,
    ACTIVATE: (id: string) => `/users/${id}/activate`,
    ROLES: (id: string) => `/users/${id}/roles`,
    REMOVE_ROLE: (id: string, role: string) => `/users/${id}/roles/${role}`,
    PERMISSIONS: (id: string) => `/users/${id}/permissions`,
    REMOVE_PERMISSION: (id: string, perm: string) => `/users/${id}/permissions/${perm}`,
    RESET_PASSWORD: (id: string) => `/users/${id}/reset-password`,
    UNLOCK: (id: string) => `/users/${id}/unlock`,
  },
  SYSTEM_SETTINGS: {
    LIST: '/system-settings',
    BY_CATEGORY: (category: string) => `/system-settings/by-category/${category}`,
    BY_KEY: (key: string) => `/system-settings/${key}`,
    SEED_DEFAULTS: '/system-settings/seed-defaults',
  },
  NODE_CONFIGURATION: {
    BY_NODE: (nodeId: string) => `/node-configuration/${nodeId}`,
    BY_CATEGORY: (nodeId: string, category: string) => `/node-configuration/${nodeId}/category/${category}`,
    UPDATE: (nodeId: string, key: string) => `/node-configuration/${nodeId}/${key}`,
    BATCH_UPDATE: (nodeId: string) => `/node-configuration/${nodeId}/batch`,
    RESET: (nodeId: string, key: string) => `/node-configuration/${nodeId}/reset/${key}`,
    RESET_CATEGORY: (nodeId: string, category: string) => `/node-configuration/${nodeId}/reset-category/${category}`,
    PUSH: (nodeId: string) => `/node-configuration/${nodeId}/push`,
    VERSION: (nodeId: string) => `/node-configuration/${nodeId}/version`,
  },
  AUDIT_LOGS: {
    LIST: '/audit-logs',
    BY_ENTITY: (entityType: string, entityId: string) => `/audit-logs/by-entity/${entityType}/${entityId}`,
    BY_CORRELATION: (correlationId: string) => `/audit-logs/by-correlation/${correlationId}`,
    EVENT_TYPES: '/audit-logs/event-types',
  },
  NODE_DICOM_ROUTING_RULES: {
    BY_NODE: (nodeId: string) => `/nodes/${nodeId}/dicom-routing-rules`,
    BY_ID:   (nodeId: string, id: string) => `/nodes/${nodeId}/dicom-routing-rules/${id}`,
    ENABLE:  (nodeId: string, id: string) => `/nodes/${nodeId}/dicom-routing-rules/${id}/enable`,
    DISABLE: (nodeId: string, id: string) => `/nodes/${nodeId}/dicom-routing-rules/${id}/disable`,
    PRIORITY:(nodeId: string, id: string) => `/nodes/${nodeId}/dicom-routing-rules/${id}/priority`,
  },
  HUB: {
    RUNTIME: '/hub/runtime',
  },
} as const;
