<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Licensing\" />
    <Folder Include="Time\" />
    <Folder Include="Worklist\" />
    <Folder Include="Routing\" />
    <Folder Include="Storage\" />
  </ItemGroup>

</Project>
